import {useEffect,useMemo,useState,type FormEvent} from 'react';
import {Activity,ArrowUpRight,BrainCircuit,ChevronDown,CircleHelp,Clock3,Database,History,Layers3,Menu,Play,Search,Target,Zap} from 'lucide-react';
import {CartesianGrid,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {getApiHealth,getBrandDashboard,getHistory,getRecommendation,getScanResult,runVisibilityScan,saveAction} from './services/api';
import type {HindsightRecord,Recommendation,ScanResult} from './types';

export default function App(){
 const [scanNo,setScanNo]=useState(1),[scan,setScan]=useState<ScanResult|null>(null),[history,setHistory]=useState<HindsightRecord|null>(null),[rec,setRec]=useState<Recommendation|null>(null),[loading,setLoading]=useState(false),[menu,setMenu]=useState(false),[snippets,setSnippets]=useState(false),[brand,setBrand]=useState(()=>localStorage.getItem('geo-agent-brand')??'Notion'),[category,setCategory]=useState(()=>localStorage.getItem('geo-agent-category')??'Project management software'),[mode,setMode]=useState<'demo'|'live'>('demo'),[apiStatus,setApiStatus]=useState<'checking'|'online'|'offline'>('checking'),[apiMode,setApiMode]=useState<'mock'|'live'>('mock'),[apiReady,setApiReady]=useState(true),[error,setError]=useState(''),[actionText,setActionText]=useState(''),[outcomeText,setOutcomeText]=useState(''),[visibilityDelta,setVisibilityDelta]=useState('0'),[savingAction,setSavingAction]=useState(false);
 async function load(n:number){setScanNo(n);setMode('demo');setBrand('Notion');setCategory('Project management software');setError('');setLoading(true);try{const [s,h,r]=await Promise.all([getScanResult(n),getHistory(),getRecommendation(n)]);setScan(s);setHistory(h);setRec(r)}finally{setLoading(false)}}
 function clearDisplayedBrandData(){setScan(null);setHistory(null);setRec(null);setScanNo(1);setMode('demo')}
 async function runScan(){setError('');clearDisplayedBrandData();setMode('live');setLoading(true);try{const result=await runVisibilityScan(brand,category);setScan(result.scan);setHistory(result.memory);setRec(result.recommendation);setScanNo(result.recommendation.scan_number);setApiStatus('online');getApiHealth().then(health=>{setApiMode(health.mode);setApiReady(health.ready)}).catch(()=>{})}catch(e){setError(e instanceof Error?e.message:'Could not run scan. Start the Python API and try again.');getApiHealth().then(health=>{setApiStatus('online');setApiMode(health.mode);setApiReady(health.ready)}).catch(()=>setApiStatus('offline'))}finally{setLoading(false)}}
 async function recordAction(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');setSavingAction(true);try{const updated=await saveAction(brand,actionText,outcomeText,Number(visibilityDelta));setHistory(updated);setActionText('');setOutcomeText('');setVisibilityDelta('0')}catch(e){setError(e instanceof Error?e.message:'Could not save the action.')}finally{setSavingAction(false)}}
 useEffect(()=>{localStorage.setItem('geo-agent-brand',brand);localStorage.setItem('geo-agent-category',category)},[brand,category]);
 useEffect(()=>{let active=true;getApiHealth().then(health=>{if(active){setApiStatus('online');setApiMode(health.mode);setApiReady(health.ready)}}).catch(()=>{if(active)setApiStatus('offline')});getBrandDashboard(brand).then(saved=>{if(!active)return;if(saved.scan&&saved.recommendation){setScan(saved.scan);setHistory(saved.history);setRec(saved.recommendation);setScanNo(saved.history.scan_history.length);setMode('live')}else{void load(1)}}).catch(()=>{if(active)void load(1)});return()=>{active=false}},[]);
 const chart=useMemo(()=>history?.scan_history.map((s,i)=>({scan:i+1,mentions:s.mentions,selected:i+1===scanNo})),[history,scanNo]);
 const ranked=useMemo(()=>Object.entries(scan?.competitors_mentioned??{}).sort((a,b)=>b[1]-a[1]),[scan]);
 const shownActions=mode==='live'?(history?.actions_log??[]):scanNo<5?[]:scanNo<10?(history?.actions_log.slice(0,Math.min(2,Math.floor((scanNo-1)/2)))??[]):(history?.actions_log??[]);
 const baselineMentions=history?.scan_history[0]?.mentions??scan?.mentions??0;
 const liftMentions=(scan?.mentions??baselineMentions)-baselineMentions;
 const maxComp=Math.max(1,...ranked.map(x=>x[1]));
 return <div className="shell">
  <aside className={`sidebar ${menu?'open':''}`}><div className="brandmark"><div className="brand-icon"><BrainCircuit size={20}/></div><div><b>GEO Agent</b><small>VISIBILITY COMMAND<br/>CENTER</small></div><button className="mobile-close" onClick={()=>setMenu(false)} aria-label="Close navigation">×</button></div>
   <div className="nav-label">WORKSPACE</div><nav><a className="nav-item active" href="#overview"><Activity size={15}/>Overview<span className="nav-active-dot"/></a><a className="nav-item" href="#history"><History size={15}/>Scan history</a><a className="nav-item" href="#memory"><Database size={15}/>Action memory</a></nav>
   <div className="loop-card"><div className="loop-title"><Zap size={13}/> MEMORY LOOP</div><p>Every scan turns action history into a sharper next move.</p><div className="loop-route"><span>Scan</span><i>→</i><span>Remember</span><i>→</i><span>Recommend</span></div><div className="loop-connected"><i/> Memory ready</div></div>
   <div className="sidebar-bottom"><div className="workspace-avatar">GT</div><div><b>Growth team</b><small>Demo workspace</small></div><CircleHelp size={14}/></div>
  </aside>
  <main id="overview" className="main"><header className="topbar"><div className="topbar-left"><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation"><Menu size={18}/></button><span className={`status-dot ${apiStatus==='offline'||!apiReady?'offline':''}`}/><span className="crumb-muted">{apiStatus==='online'?'API connected':apiStatus==='offline'?'API offline':'Checking API'}</span><span className="slash">/</span><span>GEO visibility</span></div><div className="header-right"><div className={`demo-badge ${apiStatus==='offline'||!apiReady?'api-offline':''}`}>{apiStatus==='checking'?'CHECKING LOCAL API…':apiStatus==='offline'?'API OFFLINE · START BACKEND':apiMode==='live'?(apiReady?'LIVE KEYS READY':'LIVE MODE · API KEYS NEEDED'):'API ONLINE · MOCK RESULTS'}</div><CircleHelp size={15}/></div></header>
   <div className="content"><section className="hero"><div className="eyebrow">VISIBILITY LAB <span/></div><h1>Does your brand get remembered?</h1><div className="hero-bottom"><p>Track whether AI mentions your brand — then see if the actions you take are making its<br className="wide-break"/> next recommendation smarter.</p><div className={`workspace-state ${apiStatus==='offline'||!apiReady?'offline':''}`}><i/> {apiStatus==='offline'?'API OFFLINE':apiStatus==='checking'?'CHECKING API':!apiReady?'LIVE KEYS NEEDED':'API ONLINE'} <span/><Clock3 size={13}/> {loading?'Live scan in progress':mode==='live'?'Saved brand history':'Staged dashboard data'}</div></div></section>
   <section className="control-card"><div className="brand-fields"><label>BRAND<input aria-label="Brand" value={brand} onChange={e=>{setBrand(e.target.value);clearDisplayedBrandData();setError('')}} placeholder="e.g. Notion"/></label><label>CATEGORY<input aria-label="Category" value={category} onChange={e=>{setCategory(e.target.value);clearDisplayedBrandData();setError('')}} placeholder="e.g. Project management software"/></label><button className="scan-button" onClick={()=>void runScan()} disabled={loading||!brand.trim()||!category.trim()}><Play size={13} fill="currentColor"/>{loading?'Scanning…':'Run visibility scan'}</button></div>{loading&&<div className="scan-progress" role="status">Live scan running: generating queries, searching the web, analyzing evidence, and saving results. Provider response times can vary.</div>}{apiStatus==='offline'&&<div className="scan-error" role="status">The local Python API is not responding. Start it with <code>python -m integration.api</code>, then refresh this page.</div>}{apiMode==='live'&&!apiReady&&<div className="scan-error" role="status">Live mode is selected, but provider credentials are missing. Add Groq, Tavily, and Serper keys to the project’s <code>.env</code>, then restart the Python API.</div>}{error&&<div className="scan-error" role="alert">{error}</div>}{mode==='demo'&&<div className="selector-row"><div><span className="selector-kicker">EXPLORE DEMO SCANS</span><p>Compare the staged baseline, inflection point, and mature history.</p></div><div className="selector-control">{[1,5,10].map(n=><button className={`scan-choice ${scanNo===n?'chosen':''}`} key={n} onClick={()=>void load(n)} aria-pressed={scanNo===n}><span>SCAN</span><b>{n}</b></button>)}<small>of 10 staged scans</small></div></div>}</section>
   <section className="kpis" aria-label="Visibility metrics"><article className="kpi kpi-mentions"><div className="kpi-label">BRAND MENTIONS<Target size={15}/></div><div className="kpi-value">{scan?.mentions??'—'}<small> / {scan?.total_queries??'—'}</small></div><div className="kpi-foot">Scan {scanNo} · {scan?.timestamp.slice(0,10)??'Loading'}</div></article><article className="kpi kpi-visibility"><div className="kpi-label">AI VISIBILITY<ArrowUpRight size={15}/></div><div className="kpi-value">{scan?Math.round(scan.mentions/scan.total_queries*100):'—'}<small>%</small></div><div className="kpi-foot">{liftMentions>=0?'+':''}{liftMentions} mentions vs. first scan</div></article><article className="kpi kpi-competitor"><div className="kpi-label">TOP COMPETITOR<Search size={15}/></div><div className="kpi-value word-value">{ranked[0]?.[0]??'—'}</div><div className="kpi-foot">{ranked[0]?.[1]??'—'} AI mentions</div></article><article className="kpi kpi-current"><div className="kpi-label">CURRENT SCAN<Database size={15}/></div><div className="kpi-value">#{scanNo}</div><div className="kpi-foot">{mode==='demo'?(scanNo===1?'Baseline context':scanNo===5?'Pattern-aware context':'Accumulated evidence'):`${history?.scan_history.length??scanNo} saved scans for ${brand}`}</div></article></section>
   <section className="primary-grid" id="history"><article className="panel chart-panel"><div className="panel-title"><div><h2><Activity size={15}/>Visibility over time</h2><p>{mode==='live'?'Saved scan history for this brand':'Mention rate across staged AI responses'}</p></div><div className="lift-pill"><span>LIFT</span><b>{liftMentions>=0?'+':''}{liftMentions} mentions</b></div></div><div className="chart-wrap">{chart&&<ResponsiveContainer width="100%" height="100%"><LineChart data={chart} margin={{top:14,right:12,bottom:0,left:-19}}><CartesianGrid stroke="#e9e9e4" vertical={false} strokeDasharray="3 4"/><XAxis dataKey="scan" tickFormatter={v=>`S${v}`} tick={{fill:'#8d91a3',fontSize:9}} axisLine={false} tickLine={false} dy={9}/><YAxis domain={[0,10]} ticks={[0,2,4,6,8,10]} tick={{fill:'#8d91a3',fontSize:9}} axisLine={false} tickLine={false}/><Tooltip content={({active,payload,label})=>active&&payload?.length?<div className="chart-tooltip"><small>SCAN {label}</small><b>{payload[0].value} mentions</b></div>:null}/><Line type="monotone" dataKey="mentions" stroke="#ff7355" strokeWidth={2.5} dot={({cx,cy,payload})=><circle cx={cx} cy={cy} r={payload.selected?6:3} fill={payload.selected?'#b8f500':'#fff'} stroke={payload.selected?'#222747':'#ff7355'} strokeWidth={payload.selected?2:1.6}/>} activeDot={{r:5,fill:'#b8f500',stroke:'#222747',strokeWidth:2}}/></LineChart></ResponsiveContainer>}</div><div className="chart-footer"><span>Scan 1 · baseline</span><span><i/> Selected: Scan {scanNo}</span><span>Scan {history?.scan_history.length??10} · now</span></div></article>
    <article className="panel competitor-panel"><div className="panel-title"><div><h2><Activity size={15}/>Competitive context</h2><p>Mentions in the same response set</p></div><span className="panel-meta">/{scan?.total_queries??10} queries</span></div><div className="competitor-list">{ranked.length?ranked.map(([name,value],i)=><div className="competitor-row" key={name}><div className="competitor-label"><span>{name}</span><small>{value} mentions</small></div><div className="bar-track"><span className={i===0?'bar-leader':''} style={{width:`${value/maxComp*100}%`}}/></div></div>):<div className="empty-competitors">No category competitors appeared in this scan.</div>}</div></article></section>
   <section className="evidence-grid"><article className="panel query-card"><div className="panel-title"><div><h2><Search size={15}/>Customer queries</h2><p>Prompt set used in this scan</p></div><span className="count-pill">{scan?.queries_tested.length??0} shown</span></div><ol className="query-list">{scan?.queries_tested.map((q,i)=><li key={q}><span>{String(i+1).padStart(2,'0')}</span><b>{q}</b></li>)}</ol></article>
    <article className="panel memory-card" id="memory"><div className="panel-title"><div><h2><History size={15}/>Hindsight timeline</h2><p>Actions remembered by the recommendation engine</p></div><span className="panel-meta">{shownActions.length} actions</span></div>{shownActions.length?<div className="timeline">{shownActions.map(a=><article className="timeline-item" key={a.date}><div className="timeline-marker"/><div className="action-card"><div className="action-head"><b>{a.action}</b><time>{a.date}</time></div><p>{a.outcome_summary}</p><span className="delta">{a.visibility_delta>0?'+':''}{a.visibility_delta} {Math.abs(a.visibility_delta)===1?'mention':'mentions'}</span></div></article>)}</div>:<div className="empty-memory"><b>No actions logged for {brand} yet</b><p>Log the action you tried and its observed result below to build this history.</p></div>}{mode==='live'&&<form className="action-form" onSubmit={recordAction}><label>Action tried<input value={actionText} onChange={e=>setActionText(e.target.value)} placeholder="e.g. Published a comparison page" required/></label><label>Observed result<input value={outcomeText} onChange={e=>setOutcomeText(e.target.value)} placeholder="What changed after the action?" required/></label><div className="action-form-bottom"><label>Visibility change (mentions)<input type="number" step="1" value={visibilityDelta} onChange={e=>setVisibilityDelta(e.target.value)} required/></label><button type="submit" disabled={savingAction||!actionText.trim()||!outcomeText.trim()}>{savingAction?'Saving…':'Save to Hindsight'}</button></div></form>}</article></section>
   <section className="recommendation"><div className="rec-decoration"><i/><i/><i/></div><div className="rec-top"><span className="rec-spark">✣</span><span>AGENT RECOMMENDATION</span><small>Scan {scanNo} synthesis</small></div><h2>{rec?.recommendation??'Loading recommendation…'}</h2><div className="rec-bottom"><div><span>EVIDENCE FROM MEMORY</span><p>{rec?.based_on_past_action??'No previous action — baseline recommendation'}</p></div><div className="confidence"><span>CONFIDENCE</span><p>{rec?.confidence_note??'Staged data'}</p></div></div></section>
   <section className="snippets panel"><button className="snippets-toggle" onClick={()=>setSnippets(!snippets)} aria-expanded={snippets}><div><h2><Layers3 size={15}/>Raw AI snippets <span>{scan?.raw_snippets.length??0}</span></h2></div><ChevronDown size={15} className={snippets?'rotated':''}/></button>{snippets&&<div className="snippet-body">{scan?.raw_snippets.map((s,i)=><article key={s}><span>ANSWER 0{i+1}</span><p>“{s}”</p></article>)}</div>}</section>
   <footer className="footer"><span>GEO VISIBILITY AGENT · {mode==='live'?'CONNECTED PIPELINE':'HINDSIGHT MEMORY DEMO'}</span><span>{mode==='live'?loading?`${apiMode==='mock'?'Simulated mock evidence':'Live provider evidence'} · scan is running`:`${apiMode==='mock'?'Simulated mock evidence':'Live provider evidence'} · scan saved to local memory`:'Demo data is staged for presentation'}</span></footer>
  </div></main>{menu&&<button className="scrim" aria-label="Close navigation" onClick={()=>setMenu(false)}/>}</div>
}
